version: "3.8"

services:
  db:
    image: mysql:latest
    env_file: .env.compose
    environment:
      # The actual values will be picked from .env.compose via env_file
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.compose
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped

volumes:
  db_data: {}
